### ISSUE TITLE
Track character count includes output directory name

### ISSUE THREAD

**Issue by secure-username** [RogueOneEcho/caesura#109]
When verifying, it seems to include the output directory length onto the actual length.

For example:

The name caesura chose for a potential transcode is

`./output/Various Artists - Crisis on Infinite Earths (Original Television Soundtrack) [2021] [WEB FLAC]/12.Fighting Shadows - A New Beginning (feat. Tony Kanal & Stephen Perkins).flac`

caesura includes `./output/` in the character count and concludes that it is not allowed since it is 183 characters.

However the actual name that would be used is allowed, since it is only 174 characters:

`Various Artists - Crisis on Infinite Earths (Original Television Soundtrack) [2021] [WEB FLAC]/12.Fighting Shadows - A New Beginning (feat. Tony Kanal & Stephen Perkins).flac`

**Comment by RogueOneEcho** [comment]
Thanks you are correct. This is fixed in 6ffb1282. 

There are actually numerous issues with the character count calculations. So I'll need to do a fair bit of testing before releasing the fix.

The most notable is the  https://doc.rust-lang.org/std/string/struct.String.html#method.len that was used actually returns the number of bytes rather than the number of characters. Therefore the counts were completely incorrect when album, artist or track names included accented characters, japanese, korean, emojis and such.
